---
title: "Assignment_2"
author: "Trent Buchanan"
date: "4/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(broom)
library(ggpubr)
library(patchwork)
```

```{r, include=FALSE}
abate <- read.csv(here("HW2_Water_Data_buchanan.csv")) %>% 
  clean_names()

#
```

```{r}
ag_lm <- lm(formula = mc_agriculture ~ reduced_water_use_abatement, data = abate)

ag <- abate %>% 
  select(reduced_water_use_abatement, mc_agriculture) %>% 
  mutate(line = 0.51*(reduced_water_use_abatement) + 1.94)

agplotv1 <- ggplot(data = ag, aes(x = reduced_water_use_abatement, y = mc_agriculture)) +
  geom_point() + 
  geom_smooth(method = "lm") + 
  stat_regline_equation(label.x = 75, label.y = 87.5)

agplotv2 <- ggplot() +
  geom_point(data = ag, aes(x = reduced_water_use_abatement, y = mc_agriculture)) +
  geom_line(data = ag, aes(y = line, x = reduced_water_use_abatement)) +
  annotate(geom = "text", x=50, y=75, label="y = 0.51x + 1.94") +
  theme_bw() 

agplotv2
```

```{r}
meat_lm <- lm(formula = mc_meat ~ reduced_water_use_abatement, data = abate)

meat <- abate %>% 
  select(reduced_water_use_abatement, mc_meat) %>% 
  mutate(line = 0.375 * (reduced_water_use_abatement) + 9.481)

meatplotv1 <- ggplot(data = meat, aes(x = reduced_water_use_abatement, y = mc_meat)) +
  geom_point() + 
  geom_smooth(method = "lm") + 
  stat_regline_equation(label.x = 75, label.y = 87.5)

meatplotv2 <- ggplot() +
  geom_point(data = meat, aes(x = reduced_water_use_abatement, y = mc_meat)) +
  geom_line(data = meat, aes(y = line, x = reduced_water_use_abatement)) +
  annotate(geom = "text", x=50, y=70, label="y = 0.375x + 9.481") +
  theme_bw()

meatplotv2
```

```{r}
industrial_lm <- lm(formula = mc_industrial ~ reduced_water_use_abatement, data = abate)

industrial <- abate %>% 
  select(reduced_water_use_abatement, mc_industrial) %>% 
  mutate(line = 1.13*(mc_industrial) - 26.81)

industrialplot <- ggplot() +
  geom_point(data = industrial, aes(x = reduced_water_use_abatement, y = mc_industrial)) +
  geom_line(data = industrial, aes(y = line, x = mc_industrial)) +
  annotate(geom = "text", x=50, y=150, label="y = 1.13x - 26.81") +
  theme_bw()

industrialplot

industrial_fix <- data.frame(c(0, 150)) %>% 
  rename(reduced_water_use_abatement = c.0..150.) %>% 
  mutate(line = 1.13*(reduced_water_use_abatement) - 26.81)
```

```{r}
urban_lm <- lm(formula = mc_urban ~ reduced_water_use_abatement, data = abate)

urban <- abate %>% 
  select(reduced_water_use_abatement, mc_urban) %>% 
  mutate(line = 0.597*(reduced_water_use_abatement) - 13.829)

urbanplot <- ggplot() +
  geom_point(data = urban, aes(x = reduced_water_use_abatement, y = mc_urban)) +
  geom_line(data = urban, aes(y = line, x = reduced_water_use_abatement)) +
  annotate(geom = "text", x=50, y=75, label="y = 0.597x - 13.829") +
  theme_bw()

urbanplot
```

```{r}
mcgraph <- ggplot() +
  geom_line(data = ag, aes(x = reduced_water_use_abatement, y = line), color = "green") +
  geom_line(data = meat, aes(x = reduced_water_use_abatement, y = line), color = "red") +
  geom_line(data = industrial_fix, aes(y = line, x = reduced_water_use_abatement), color = "grey") +
  geom_line(data = urban, aes(x = reduced_water_use_abatement, y = line), color = "black") +
  labs(x = "Water Use Abatement, AF (Q)", y = "$/AF Abatement (P)") +
  theme_bw()

mcgraph
```



```{r}
ag_inv <- abate %>% 
  select(reduced_water_use_abatement, d_ag)

ag_invplot <- ggplot(data = ag_inv) +
  geom_line(aes(x = reduced_water_use_abatement, y = d_ag)) +
  geom_point(aes(x = reduced_water_use_abatement, y = d_ag)) +
  theme_bw()

ag_invplot
```

```{r}
meat_inv <- abate %>% 
  select(reduced_water_use_abatement, d_meat)

meat_invplot <- ggplot(data = meat_inv) +
  geom_line(aes(x = reduced_water_use_abatement, y = d_meat)) +
  geom_point(aes(x = reduced_water_use_abatement, y = d_meat)) +
  theme_bw()

meat_invplot
```

```{r}
industrial_inv <- abate %>% 
  select(reduced_water_use_abatement, d_industrial)

industrial_invplot <- ggplot(data = industrial_inv) +
  geom_line(aes(x = reduced_water_use_abatement, y = d_industrial)) +
  geom_point(aes(x = reduced_water_use_abatement, y = d_industrial)) +
  theme_bw()

industrial_invplot
```

```{r}
urban_inv <- abate %>% 
  select(reduced_water_use_abatement, d_urban)

urban_invplot <- ggplot(data = urban_inv) +
  geom_line(aes(x = reduced_water_use_abatement, y = d_urban)) +
  geom_point(aes(x = reduced_water_use_abatement, y = d_urban)) +
  theme_bw()

urban_invplot
```

```{r}
agplotv2 + meatplotv2 + industrialplot + urbanplot +
  plot_annotation(tag_levels = "a")

fullmcplot <- ggplot() +
  #geom_line(data = ag, aes(x = reduced_water_use_abatement, y = line)) +
  geom_line(data = meat, aes(x = reduced_water_use_abatement, y = line)) +
  #geom_line(data = industrial, aes(x = reduced_water_use_abatement, y = line)) +
  geom_line(data = urban, aes(x = reduced_water_use_abatement, y = line)) +
  theme_bw()

fullmcplot
```


```{r}
aggregateplot <- ggplot() +
  geom_line(data = urban_inv, aes(x= reduced_water_use_abatement, y = d_urban), color = "black") +
  geom_line(data = ag_inv, aes(x = reduced_water_use_abatement, y = d_ag), color = "green") +
  geom_line(data = industrial_inv, aes(x = reduced_water_use_abatement, y = d_industrial), color = "grey") +
  geom_line(data = meat_inv, aes(x = reduced_water_use_abatement, y = d_meat), color = "red") +
  labs(x = "Water Use, AF (Q)", y = "$/AF Water (P)") +
  theme_bw()

aggregateplot
```
